### ISSUE TITLE
title에서 방향키 아래 사용시 crash 발생

### ISSUE THREAD

**Issue by imssm99** [SSM-and-etc/Uno_SE#71]
```
Traceback (most recent call last):
  File "/Users/imssm99/Uno_SE/Script/game_main.py", line 145, in <module>
    gameMain.play()
  File "/Users/imssm99/Uno_SE/Script/game_main.py", line 131, in play
    self.get_scene_obj(self.scene_state).display(self)
  File "/Users/imssm99/Uno_SE/Script/Title/title.py", line 47, in display
    self.keydown_title(main, event.key)
  File "/Users/imssm99/Uno_SE/Script/Title/title.py", line 77, in keydown_title
    if self.buttons.key_down_state(key):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/imssm99/Uno_SE/Script/System/statebuttons.py", line 58, in key_down_state
    if self.state[1] >= len(self.imgs[self.state[0]]):
                            ~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by pianoop** [comment]
[pull request](https://github.com/SSM-and-etc/Uno_SE/pull/70)
에서 해결했습니다!
